name: deploy Infra

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-rw:
    uses: devandalo/tf-workflows-juno/.github/workflows/deploy-infra-tmpl.yml@main
    secrets: inherit
