name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy tf-composition?"
        required: true
        type: boolean
        default: false

  push:
    branches:
      - main

jobs:
  test-rw:
    uses: devandalo/tf-workflows-juno/.github/workflows/deploy-infra-tmpl.yml@main
    secrets: inherit
    with:
      environment: "lab"
