name: DESTROY

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy tf-composition?"
        required: true
        type: boolean
        default: false

jobs:
  deploy-infra:
    uses: devandalo/tf-workflows-juno/.github/workflows/deploy-infra-tmpl.yml@main
    secrets: inherit
    with:
      environment: "lab"
      destroy: ${{ inputs.destroy }}
