name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test-rw:
    uses: devandalo/tf-workflows-juno/.github/workflows/pr-tmpl.yml@main
    secrets: inherit
    with:
      environment: "lab"
      destroy: true
